# Generated by Django 3.2.4 on 2021-06-26 18:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.CharField(blank=True, default=datetime.datetime.now, max_length=200, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('regnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('dats', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regnumber', models.CharField(max_length=200)),
                ('dats', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=200)),
                ('casetype', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('emergency', models.BooleanField()),
                ('user_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repo.evident')),
                ('user_weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repo.weakness')),
            ],
        ),
    ]
